# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#- task: DotNetCoreCLI@3
#  inputs:
#    solution: '$(solution)'
#    msbuildArgs: '/p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\testWebApi.zip"'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

#
#- task: VSTest@2
# inputs:
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'
#

- task: DotNetCoreCLI@2   
  displayName: Build
  inputs:
    command: build
    solution: '**/*.sln'
    arguments: '/p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\testWebApi.zip"'

- task: DotNetCoreCLI@2   
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-webapi-serviceconnection'
    appName: 'testWebApi'
    package: $(System.ArtifactsDirectory)/**/*.z
